// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeyoydltgoftjnaqcwky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlleW95ZGx0Z29mdGpuYXFjd2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODQzNDMsImV4cCI6MjA3NDA2MDM0M30.ifjWBFHsrWy90Yd5o8vYN3GkS4mH3u9TtgJJ7kcIelw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});